### ISSUE TITLE
WEB: Create new format developments page

### ISSUE THREAD

**Issue by odontaster** [ices-eg/WGDG#2]
After a suggestion from Neil, we will create an info page similar to this one 
https://www.ices.dk/data/data-portals/Pages/ocean-format.aspx
 where we detail the latest format changes, field adittions etc, requests or mandate to these and deadlines.

**Comment by odontaster** [comment]
Ready now: 
https://www.ices.dk/data/data-portals/Pages/Datras_news_and_updates.aspx

**Comment by odontaster** [comment]
Pending comments from WGBEAM and also from WGDG

**Comment by Ingeborg1312** [comment]
With respect to the news and updates: the content is fine. Maybe an overview with clear date stamps, the most recent coming first, will ease reading, e.g.:
----------------------------------------------
Format updates
2022-Q3 
In order to allow the addition of new fields minimising the impact on the rest of the surveys, DATRAS only accepts submissions without headers. This allows for addition of new fields upon request for different DATRAS stakeholders without requiring format changes for all submitters.​

A new field has been added to the CA records: ​LiverWeight. This field was requested by [BITS in 2020](https://ices-library.figshare.com/articles/report/Working_Group_on_Baltic_International_Fish_Survey_WGBIFS_/18618428).

​​2020-Q4 
Adoption of  the [unified format](https://datras.ices.dk/Data_products/ReportingFormat.aspx), equal through DATRAS surveys, following a 2020 resolution from the [DATRAS Governance group](https://ices-library.figshare.com/articles/report/Working_Group_on_DATRAS_Governance_WGDG_/19248899).
Adoption and introduction of the format with headers (previously submissions without headers were accepted). This change allows submissions of only desired variables and leaves out unused fields, reducing the file size and simplifying the format conversions. 
----------------------------------------

What I really miss is a clear link on https://www.ices.dk/data/data-portals/Pages/DATRAS.aspx. I would propose that we add a line to the body text on that page: "DATRAS is updated frequently. Information on format changes or changed vocabulary can be found here:  https://www.ices.dk/data/data-portals/Pages/Datras_news_and_updates.aspx"
