### ISSUE TITLE
WEB: New format landing page

### ISSUE THREAD

**Issue by odontaster** [ices-eg/WGDG#4]
Before the individuals surveys format description of mandatory fields, there will be a landing page with a simple yet clear description of the format and a downloadable spread sheet with all fields descriptions, with links to vocasb, plus a test file with the correct headers

**Comment by odontaster** [comment]
waiting for feedback from WGBEAM and WGDG

**Comment by odontaster** [comment]
https://www.ices.dk/data/data-portals/Pages/DATRAS_format_description.aspx

**Comment by Ingeborg1312** [comment]
Seems to be ok with me, but I'd like some less experienced datras submitters comment on it. I wonder if you should mention the number of fields per record type, as that may easily change with the new format. So maybe 'more than 25'/ 'more than 30'/'more than 20' may be the safer option if we really feel the need to provide some numbers, but otherwise e.g.

HH record type
The fields in this record type represent the haul characteristics, such as date, time, coordinates, gear specifications, haul duration and distance, and environmental conditions.

HL record type
(...) The fields in this type allow amongst other for recording subsampling and categorisation of the catch, length measurements and the measurement units, weight recording, numbers caught.

CA record type
This record type is linked with HL records by species and length class. In the CA record type, biological information for individual fish is reported, such as length, weight, sex, sexual maturity stage, age.

A change in bold (HL) and an addition in italics (CA) below.

HL record type
In this record type, length distribution of species **is** described. There are up to 26 available fields that allow this type of recording, including subsampling schemes and categorisation of the catch.

CA record type
This record type is linked with HL records by species and length class. In the CA record type, there are 31 available fields that allow the reporting of age, maturity and several other biological measurements such as genetic, stomach and liver samplings, among others.
_When a species is reported in CA, also a record in HL should be available for that species, even if all information is marked as '-9' (missing information)._

**Comment by odontaster** [comment]
implemented
